apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
    tier: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tier: zabbix
  template:
    metadata:
      labels:
        app: grafana
        tier: zabbix
    spec:
      containers:
      - image: grafana/grafana:latest
        name: grafana
        env:        
          - name: GF_INSTALL_PLUGINS
            value: alexanderzobnin-zabbix-app
        ports:
        - containerPort: 3000
          name: zabbix
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    tier: zabbix