apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    usage: mysql-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: mysql
    readOnly: false
