apiVersion: v1
kind: PersistentVolume
metadata:
  name: internal-storage
  # The label is used for matching the exact claim
  labels:
    usage: internal-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: internalscripts
    readOnly: false