apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-storage
  # The label is used for matching the exact claim
  labels:
    usage: external-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    secretName: azure-secret
    shareName: externalscripts
    readOnly: false