apiVersion: v1
kind: Service
metadata:
  name: zabbix-service
  labels:
    app: zabbix-service
spec:
  type: NodePort
  ports:
  - port: 10051
  selector:
    app: zabbix-server
    tier: zabbix
